<?php
// contact.php — Contact form receiver for "Zenith Studio". Auto-generated by WebCraft AI.
// Sends visitor messages to the site owner via the platform mailer (no owner password needed).
header('Content-Type: application/json');
header('X-Content-Type-Options: nosniff');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed']);
    exit;
}

// Honeypot (bots fill it, humans don't)
if (!empty($_POST['company'])) { echo json_encode(['success' => true]); exit; }

function pick($keys) {
    foreach ($keys as $k) {
        if (!empty($_POST[$k]) && is_string($_POST[$k])) return trim($_POST[$k]);
    }
    return '';
}
$name    = strip_tags(pick(['name', 'your-name', 'full-name', 'fullname']));
$email   = trim(pick(['email', 'your-email', 'email-address']));
$phone   = strip_tags(pick(['phone', 'your-phone', 'tel', 'mobile']));
$message = strip_tags(pick(['message', 'your-message', 'comments', 'comment', 'enquiry']));

if ($name === '' || $message === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => 'Please fill your name, a valid email and your message.']);
    exit;
}
if (strlen($message) > 5000) $message = substr($message, 0, 5000);

// Basic per-IP throttle: 20/hour
$ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
$hitsFile = __DIR__ . '/contact_hits.json';
$hits = file_exists($hitsFile) ? (json_decode(@file_get_contents($hitsFile), true) ?: []) : [];
$now = time();
$hits = array_values(array_filter($hits, function ($h) use ($now, $ip) {
    return is_array($h) && ($now - ($h['t'] ?? 0)) < 3600 && ($h['ip'] ?? '') === $ip;
}));
if (count($hits) >= 20) {
    http_response_code(429);
    echo json_encode(['success' => false, 'error' => 'Too many messages. Please try again later.']);
    exit;
}
$hits[] = ['ip' => $ip, 't' => $now];
@file_put_contents($hitsFile, json_encode($hits));

require dirname(dirname(__DIR__)) . '/includes/Mailer.php';

$subject = 'New website enquiry — Zenith Studio';
$bodyHtml = '<div style="font-family:Segoe UI,Arial,sans-serif;color:#111;padding:20px;">'
    . '<h2 style="margin:0 0 12px;">New enquiry from your website</h2>'
    . '<p><strong>Name:</strong> ' . htmlspecialchars($name) . '<br>'
    . '<strong>Email:</strong> ' . htmlspecialchars($email) . '<br>'
    . '<strong>Phone:</strong> ' . htmlspecialchars($phone ?: '—') . '</p>'
    . '<div style="background:#f3f4f6;border-radius:10px;padding:14px;white-space:pre-wrap;">' . htmlspecialchars($message) . '</div>'
    . '<p style="color:#6b7280;font-size:12px;">Reply directly to ' . htmlspecialchars($email) . '.</p></div>';

$res = Mailer::send('senthustr01@gmail.com', $subject, $bodyHtml, "Name: {$name}
Email: {$email}
Phone: {$phone}

{$message}");
if (!empty($res['success'])) {
    echo json_encode(['success' => true]);
} else {
    http_response_code(500);
    echo json_encode(['success' => false, 'error' => 'Mail server busy. Please try again later.']);
}